/*
  PARTIE I
*/
/*Creation de la table */
DROP TABLE D_VENTE_MEDICAMENTS;
CREATE TABLE D_VENTE_MEDICAMENTS(
SECTOR_ID VARCHAR2(50) NOT NULL,
TIME_ID VARCHAR2(50) NOT NULL,
ID_MEDICAMENT VARCHAR2(50) NOT NULL,
CA INTEGER,
MARGE INTEGER
)
TABLESPACE USERS;
ALTER TABLE D_VENTE_MEDICAMENTS ADD PRIMARY KEY (SECTOR_ID, TIME_ID, ID_MEDICAMENT);

/*Insertion dans la table*/
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'ASPEGIC', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'ASPEGIC', 300, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'ADALATE', 250, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ASPEGIC', 175, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'ASPEGIC', 212, 63);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'ASPEGIC', 221, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'ADALATE', 123, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ASPEGIC', 124, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'ASPEGIC', 66, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'ASPEGIC', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'ASPEGIC', 142, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ASPEGIC', 854, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'FELDENE', 154, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ADALATE', 140, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'PROFENID', 150, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'FELDENE', 165, 23);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'PROFENID', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ADALATE', 210, 37);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'FELDENE', 133, 44);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'FELDENE', 154, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'PROFENID', 66, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ADALATE', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201101', 'FELDENE', 162, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201104', 'FELDENE', 784, 36);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201103', 'ASPEGIC', 142, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201102', 'GLUCOPHAGE', 142, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201107', 'LOXEN', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201105', 'DOLIPRANE', 444, 120);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201106', 'GLUCOPHAGE', 331, 112);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201110', 'GLUCOPHAGE', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201109', 'GLUCOPHAGE', 1200, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201108', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201112', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'ASPEGIC', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'ASPEGIC', 290, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'ADALATE', 240, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ASPEGIC', 165, 57);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'ASPEGIC', 202, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'ASPEGIC', 211, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'ADALATE', 113, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ASPEGIC', 114, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'ASPEGIC', 56, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'ASPEGIC', 45, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'ASPEGIC', 132, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ASPEGIC', 844, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'FELDENE', 2000, 6);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ADALATE', 130, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'PROFENID', 140, 49);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'FELDENE', 155, 20);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'PROFENID', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ADALATE', 200, 34);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'FELDENE', 123, 41);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'FELDENE', 144, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'PROFENID', 56, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ADALATE', 20001, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201101', 'FELDENE', 152, 8);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201104', 'FELDENE', 774, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201103', 'ASPEGIC', 132, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201102', 'GLUCOPHAGE', 132, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201107', 'LOXEN', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201105', 'DOLIPRANE', 434, 117);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201106', 'GLUCOPHAGE', 321, 109);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201110', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201109', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201108', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201112', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201001', 'ASPEGIC', 108, 25);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201002', 'ASPEGIC', 288, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201003', 'ADALATE', 238, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201004', 'ASPEGIC', 163, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201005', 'ASPEGIC', 200, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201006', 'ASPEGIC', 209, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201007', 'ADALATE', 111, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201008', 'ASPEGIC', 112, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201009', 'ASPEGIC', 54, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'ASPEGIC', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'ASPEGIC', 292, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201003', 'ADALATE', 242, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201004', 'ASPEGIC', 167, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201005', 'ASPEGIC', 204, 61);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201006', 'ASPEGIC', 213, 15);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201007', 'ADALATE', 115, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201008', 'ASPEGIC', 116, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201009', 'FELDENE', 58, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201010', 'ASPEGIC', 47, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201011', 'GLUCOPHAGE', 10000, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201012', 'DIAMICRON', 846, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S5', '201012', 'DIAMICRON', 2145, 26);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S7', '201110', 'GLUCOPHAGE', 4578, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'DIAMICRON', 8461, 214);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'DIAMICRON', 1458, 124);

INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201102', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'FELDENE', 1457, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201111', 'GLUCOPHAGE', 45789, 2457);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201101', 'ASPEGIC', 1456, 128);
COMMIT;

/*Creation de la vue matérilise de ventre medicament*/
DROP MATERIALIZED VIEW MV_VENTE_MEDICAMENTS;
CREATE MATERIALIZED VIEW MV_VENTE_MEDICAMENTS FOR UPDATE
AS
SELECT * FROM D_VENTE_MEDICAMENTS;

/*Creation trigger pour mettre a jour la vue materialiser*/
CREATE OR REPLACE TRIGGER TRG_MAJ_MV_VENTE_MEDICAMENTS
AFTER INSERT OR UPDATE OR DELETE
ON D_VENTE_MEDICAMENTS
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    DBMS_OUTPUT.PUT_LINE('Insertion de la vue MV_VENTE_MEDICAMENTS');
    INSERT INTO MV_VENTE_MEDICAMENTS (SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
    VALUES (:NEW.sector_id,:NEW.time_id, :NEW.id_MEDICAMENT, :NEW.CA, :NEW.MARGE);
  ELSIF DELETING THEN
    DBMS_OUTPUT.PUT_LINE('Suppresion de la vue MV_VENTE_MEDICAMENTS');
    DELETE FROM MV_VENTE_MEDICAMENTS
    WHERE SECTOR_ID = :OLD.SECTOR_ID and TIME_ID = :OLD.TIME_ID and ID_MEDICAMENT = :OLD.ID_MEDICAMENT and CA = :OLD.CA and  MARGE = :OLD.MARGE;
  ELSE
    DBMS_OUTPUT.PUT_LINE('Modification  de la vue MV_VENTE_MEDICAMENTS');
    UPDATE MV_VENTE_MEDICAMENTS
    SET SECTOR_ID = :NEW.SECTOR_ID , TIME_ID = :NEW.TIME_ID , ID_MEDICAMENT = :NEW.ID_MEDICAMENT , CA = :NEW.CA ,  MARGE = :NEW.MARGE
    WHERE SECTOR_ID = :OLD.SECTOR_ID and TIME_ID = :OLD.TIME_ID and ID_MEDICAMENT = :OLD.ID_MEDICAMENT and CA = :OLD.CA and  MARGE = :OLD.MARGE;
  END IF;
END;
/

/*
  FIN PARTIE I
*/

/*
  PARTIE II
*/

/*Creation de la table client*/
DROP TABLE CLIENT;
CREATE TABLE CLIENT
(
CD_PAYS VARCHAR2(10), ID_APPLI VARCHAR2(30),
ID_FINANC VARCHAR2(30), ID_CLT VARCHAR2(30),
CD_STATUT VARCHAR2(10), DER_NUM_CTL VARCHAR2(10),
ID_DER_DEMAND VARCHAR2(30), NOTE_CLIENT NUMBER(10,3),
POURCENT_PERTE NUMBER(10,3)
);

/*Insertion dans la table client*/
INSERT INTO CLIENT
(CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT, CD_STATUT, DER_NUM_CTL, ID_DER_DEMAND,
NOTE_CLIENT, POURCENT_PERTE)
VALUES
('FR', '01', 'fin1', 'clt1', 'C', ' ', '1', 50, 20);
INSERT INTO CLIENT
(CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT, CD_STATUT, DER_NUM_CTL, ID_DER_DEMAND,
NOTE_CLIENT, POURCENT_PERTE)
VALUES
('FR', '01', 'fin2', 'clt1', 'C', ' ', '2', 52, 15);
INSERT INTO CLIENT
(CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT, CD_STATUT, DER_NUM_CTL, ID_DER_DEMAND,
NOTE_CLIENT, POURCENT_PERTE)
VALUES
('FR', '01', 'fin3', 'clt2', 'C', ' ', '3', 88, 5);
INSERT INTO CLIENT
(CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT, CD_STATUT, DER_NUM_CTL, ID_DER_DEMAND,
NOTE_CLIENT, POURCENT_PERTE)
VALUES
('FR', '01', 'fin3', 'clt2', 'C', ' ', '3', 88, 5);
INSERT INTO CLIENT
(CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT, CD_STATUT, DER_NUM_CTL, ID_DER_DEMAND,
NOTE_CLIENT, POURCENT_PERTE)
VALUES
('FR', '01', 'fin3', 'clt2', 'C', ' ', '3', 88, 5);
INSERT INTO CLIENT
(CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT, CD_STATUT, DER_NUM_CTL, ID_DER_DEMAND,
NOTE_CLIENT, POURCENT_PERTE)
VALUES
('FR', '01', 'fin3', 'clt2', 'C', ' ', '3', 88, 5);
COMMIT;

/*Affichage du contenu*/
SELECT * FROM client;

/*Afficher des doublons*/
SELECT CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT, COUNT(*) FROM CLIENT GROUP BY CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT
HAVING COUNT(*) > 1;

/*Afficher toutes les lignes en double*/
SELECT * FROM CLIENT
WHERE CD_PAYS||''||ID_APPLI||''||ID_FINANC||''||ID_CLT||''||CD_STATUT||''||DER_NUM_CTL||''||ID_DER_DEMAND||''||NOTE_CLIENT||''||POURCENT_PERTE IN (
SELECT CD_PAYS||''||ID_APPLI||''||ID_FINANC||''||ID_CLT||''||CD_STATUT||''||DER_NUM_CTL||''||ID_DER_DEMAND||''||NOTE_CLIENT||''||POURCENT_PERTE
FROM CLIENT GROUP BY CD_PAYS, ID_APPLI, ID_FINANC, DER_NUM_CTL, ID_CLT, NOTE_CLIENT ,POURCENT_PERTE, CD_STATUT, ID_DER_DEMAND
HAVING COUNT(*) > 1);

/*Supprimer tous les doublons*/
DELETE FROM client
WHERE CD_PAYS||''||ID_APPLI||''||ID_FINANC||''||ID_CLT||''||CD_STATUT||''||DER_NUM_CTL||''||ID_DER_DEMAND||''||NOTE_CLIENT||''||POURCENT_PERTE IN (
SELECT CD_PAYS||''||ID_APPLI||''||ID_FINANC||''||ID_CLT||''||CD_STATUT||''||DER_NUM_CTL||''||ID_DER_DEMAND||''||NOTE_CLIENT||''||POURCENT_PERTE
FROM CLIENT GROUP BY CD_PAYS, ID_APPLI, ID_FINANC, DER_NUM_CTL, ID_CLT, NOTE_CLIENT ,POURCENT_PERTE, CD_STATUT, ID_DER_DEMAND
HAVING COUNT(*) > 1);

/*Suprimme tous les doublons sauf un pour CD_PAYS=DE*/
DELETE FROM client
WHERE CD_PAYS = 'DE'
AND ROWID IN (
  SELECT ROWID FROM client WHERE ROWID NOT IN (
    SELECT MIN(ROWID) FROM CLIENT GROUP BY CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT
  )
);

/*Suprimme tous les doublons sauf un pour CD_PAYS=FR*/
DELETE FROM client
WHERE CD_PAYS = 'FR'
AND ROWID IN (
  SELECT ROWID FROM client WHERE ROWID NOT IN (
    SELECT MIN(ROWID) FROM CLIENT GROUP BY CD_PAYS, ID_APPLI, ID_FINANC, ID_CLT
  )
);

/*
  FIN PARTIE II
*/

/*
  PARTIE III
*/
/*Creation d'une table de trvail similaire a la table CLIENT*/
DROP TABLE W_CLIENT;
CREATE TABLE W_CLIENT AS SELECT * FROM CLIENT;

/*Création de l'index sur la table w_client*/
DROP INDEX idx1_w_clt ;
CREATE INDEX idx1_w_clt ON w_client (CD_PAYS, ID_CLT);

/*Execution de la requete dynamique */
SELECT owner ,object_name,object_type,status FROM dba_objects WHERE owner = (SELECT user FROM dual) AND
status!= 'VALID';

/*Affichage de la liste des tablespaces*/
select * from DBA_TABLESPACES;

/*Afficher le tablespace de la table w_client*/
SELECT owner, table_name, tablespace_name FROM dba_tables WHERE table_name='W_CLIENT';

/*Déplacer le tablespace dans un autre*/
ALTER TABLE W_CLIENT MOVE TABLESPACE USERS;

/*Executer la requete suivante*/
SELECT owner, object_name,object_type,status FROM dba_objects WHERE owner = (SELECT user FROM dual) AND
status != 'VALID';

CREATE OR REPLACE PROCEDURE deleteByObjectType(myType IN VARCHAR, myUser IN VARCHAR)
IS
BEGIN
  FOR line IN (SELECT object_name FROM ALL_OBJECTS WHERE status != 'VALID' AND object_type=UPPER(myType)
  AND owner=UPPER(myUser)) LOOP
    EXECUTE IMMEDIATE 'DROP ' || UPPER(myType) || ' ' || line.object_name;
    DBMS_OUTPUT.put_line(line.object_name || ' deleted !');
  END LOOP;
END;
/

exec deleteByObjectType('procedure', 'malekus');

/*
  FINN PARTIE III
*/


/********************************************/
/********************PARTIE 4****************/
/********************************************/

/*IV-1*/
SELECT * FROM NLS_INSTANCE_PARAMETERS;
select value from NLS_DATABASE_PARAMETERS where parameter ='NLS_DATE_FORMAT';
SELECT * FROM NLS_SESSION_PARAMETERS;
/*IV-2*/
select * from D_VENTE_MEDICAMENTS where time_id=?20/10/2001?;
/*IV-3*/
alter session set nls_date_format = 'yyyymm';
truncate table D_VENTE_MEDICAMENTS;
/*Insertion dans la table*/
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'ASPEGIC', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'ASPEGIC', 300, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'ADALATE', 250, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ASPEGIC', 175, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'ASPEGIC', 212, 63);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'ASPEGIC', 221, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'ADALATE', 123, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ASPEGIC', 124, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'ASPEGIC', 66, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'ASPEGIC', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'ASPEGIC', 142, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ASPEGIC', 854, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'FELDENE', 154, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ADALATE', 140, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'PROFENID', 150, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'FELDENE', 165, 23);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'PROFENID', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ADALATE', 210, 37);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'FELDENE', 133, 44);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'FELDENE', 154, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'PROFENID', 66, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ADALATE', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201101', 'FELDENE', 162, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201104', 'FELDENE', 784, 36);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201103', 'ASPEGIC', 142, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201102', 'GLUCOPHAGE', 142, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201107', 'LOXEN', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201105', 'DOLIPRANE', 444, 120);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201106', 'GLUCOPHAGE', 331, 112);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201110', 'GLUCOPHAGE', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201109', 'GLUCOPHAGE', 1200, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201108', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201112', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'ASPEGIC', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'ASPEGIC', 290, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'ADALATE', 240, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ASPEGIC', 165, 57);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'ASPEGIC', 202, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'ASPEGIC', 211, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'ADALATE', 113, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ASPEGIC', 114, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'ASPEGIC', 56, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'ASPEGIC', 45, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'ASPEGIC', 132, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ASPEGIC', 844, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'FELDENE', 2000, 6);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ADALATE', 130, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'PROFENID', 140, 49);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'FELDENE', 155, 20);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'PROFENID', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ADALATE', 200, 34);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'FELDENE', 123, 41);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'FELDENE', 144, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'PROFENID', 56, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ADALATE', 20001, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201101', 'FELDENE', 152, 8);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201104', 'FELDENE', 774, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201103', 'ASPEGIC', 132, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201102', 'GLUCOPHAGE', 132, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201107', 'LOXEN', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201105', 'DOLIPRANE', 434, 117);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201106', 'GLUCOPHAGE', 321, 109);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201110', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201109', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201108', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201112', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201001', 'ASPEGIC', 108, 25);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201002', 'ASPEGIC', 288, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201003', 'ADALATE', 238, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201004', 'ASPEGIC', 163, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201005', 'ASPEGIC', 200, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201006', 'ASPEGIC', 209, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201007', 'ADALATE', 111, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201008', 'ASPEGIC', 112, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201009', 'ASPEGIC', 54, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'ASPEGIC', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'ASPEGIC', 292, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201003', 'ADALATE', 242, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201004', 'ASPEGIC', 167, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201005', 'ASPEGIC', 204, 61);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201006', 'ASPEGIC', 213, 15);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201007', 'ADALATE', 115, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201008', 'ASPEGIC', 116, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201009', 'FELDENE', 58, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201010', 'ASPEGIC', 47, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201011', 'GLUCOPHAGE', 10000, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201012', 'DIAMICRON', 846, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S5', '201012', 'DIAMICRON', 2145, 26);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S7', '201110', 'GLUCOPHAGE', 4578, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'DIAMICRON', 8461, 214);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'DIAMICRON', 1458, 124);

INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201102', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'FELDENE', 1457, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201111', 'GLUCOPHAGE', 45789, 2457);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201101', 'ASPEGIC', 1456, 128);
COMMIT;
select * from D_VENTE_MEDICAMENTS where time_id=?20/10/2001?;

/*refaisons avec time_id au type date*/
DROP TABLE D_VENTE_MEDICAMENTS;
CREATE TABLE D_VENTE_MEDICAMENTS(
SECTOR_ID VARCHAR2(50) NOT NULL,
TIME_ID DATE NOT NULL,
ID_MEDICAMENT VARCHAR2(50) NOT NULL,
CA INTEGER,
MARGE INTEGER
)
TABLESPACE USERS;
ALTER TABLE D_VENTE_MEDICAMENTS ADD PRIMARY KEY (SECTOR_ID, TIME_ID, ID_MEDICAMENT);

/*Insertion dans la table*/
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'ASPEGIC', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'ASPEGIC', 300, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'ADALATE', 250, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ASPEGIC', 175, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'ASPEGIC', 212, 63);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'ASPEGIC', 221, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'ADALATE', 123, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ASPEGIC', 124, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'ASPEGIC', 66, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'ASPEGIC', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'ASPEGIC', 142, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ASPEGIC', 854, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'FELDENE', 154, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ADALATE', 140, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'PROFENID', 150, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'FELDENE', 165, 23);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'PROFENID', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ADALATE', 210, 37);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'FELDENE', 133, 44);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'FELDENE', 154, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'PROFENID', 66, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ADALATE', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201101', 'FELDENE', 162, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201104', 'FELDENE', 784, 36);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201103', 'ASPEGIC', 142, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201102', 'GLUCOPHAGE', 142, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201107', 'LOXEN', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201105', 'DOLIPRANE', 444, 120);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201106', 'GLUCOPHAGE', 331, 112);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201110', 'GLUCOPHAGE', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201109', 'GLUCOPHAGE', 1200, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201108', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201112', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'ASPEGIC', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'ASPEGIC', 290, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'ADALATE', 240, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ASPEGIC', 165, 57);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'ASPEGIC', 202, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'ASPEGIC', 211, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'ADALATE', 113, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ASPEGIC', 114, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'ASPEGIC', 56, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'ASPEGIC', 45, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'ASPEGIC', 132, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ASPEGIC', 844, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'FELDENE', 2000, 6);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ADALATE', 130, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'PROFENID', 140, 49);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'FELDENE', 155, 20);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'PROFENID', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ADALATE', 200, 34);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'FELDENE', 123, 41);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'FELDENE', 144, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'PROFENID', 56, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ADALATE', 20001, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201101', 'FELDENE', 152, 8);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201104', 'FELDENE', 774, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201103', 'ASPEGIC', 132, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201102', 'GLUCOPHAGE', 132, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201107', 'LOXEN', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201105', 'DOLIPRANE', 434, 117);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201106', 'GLUCOPHAGE', 321, 109);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201110', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201109', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201108', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201112', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201001', 'ASPEGIC', 108, 25);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201002', 'ASPEGIC', 288, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201003', 'ADALATE', 238, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201004', 'ASPEGIC', 163, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201005', 'ASPEGIC', 200, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201006', 'ASPEGIC', 209, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201007', 'ADALATE', 111, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201008', 'ASPEGIC', 112, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201009', 'ASPEGIC', 54, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'ASPEGIC', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'ASPEGIC', 292, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201003', 'ADALATE', 242, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201004', 'ASPEGIC', 167, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201005', 'ASPEGIC', 204, 61);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201006', 'ASPEGIC', 213, 15);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201007', 'ADALATE', 115, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201008', 'ASPEGIC', 116, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201009', 'FELDENE', 58, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201010', 'ASPEGIC', 47, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201011', 'GLUCOPHAGE', 10000, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201012', 'DIAMICRON', 846, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S5', '201012', 'DIAMICRON', 2145, 26);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S7', '201110', 'GLUCOPHAGE', 4578, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'DIAMICRON', 8461, 214);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'DIAMICRON', 1458, 124);

INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201102', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'FELDENE', 1457, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201111', 'GLUCOPHAGE', 45789, 2457);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201101', 'ASPEGIC', 1456, 128);
COMMIT;
/*IV-2*/
select * from D_VENTE_MEDICAMENTS where time_id=?20/10/2001?;
/*IV-3*/
alter session set nls_date_format = 'yyyymm';
truncate table D_VENTE_MEDICAMENTS;
/*Insertion dans la table*/
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'ASPEGIC', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'ASPEGIC', 300, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'ADALATE', 250, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ASPEGIC', 175, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'ASPEGIC', 212, 63);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'ASPEGIC', 221, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'ADALATE', 123, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ASPEGIC', 124, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'ASPEGIC', 66, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'ASPEGIC', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'ASPEGIC', 142, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ASPEGIC', 854, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201001', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201002', 'FELDENE', 120, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201003', 'FELDENE', 154, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201004', 'ADALATE', 140, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201005', 'PROFENID', 150, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201006', 'FELDENE', 165, 23);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201007', 'PROFENID', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201008', 'ADALATE', 210, 37);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201009', 'FELDENE', 133, 44);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201010', 'FELDENE', 154, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201011', 'PROFENID', 66, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201012', 'ADALATE', 55, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201101', 'FELDENE', 162, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201104', 'FELDENE', 784, 36);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201103', 'ASPEGIC', 142, 17);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201102', 'GLUCOPHAGE', 142, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201107', 'LOXEN', 124, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201105', 'DOLIPRANE', 444, 120);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201106', 'GLUCOPHAGE', 331, 112);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201110', 'GLUCOPHAGE', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201109', 'GLUCOPHAGE', 1200, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201108', 'AVLOCARDYL', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201111', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S1', '201112', 'DIAMICRON', 256, 16);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'ASPEGIC', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'ASPEGIC', 290, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'ADALATE', 240, 52);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ASPEGIC', 165, 57);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'ASPEGIC', 202, 60);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'ASPEGIC', 211, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'ADALATE', 113, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ASPEGIC', 114, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'ASPEGIC', 56, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'ASPEGIC', 45, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'ASPEGIC', 132, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ASPEGIC', 844, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201001', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201002', 'FELDENE', 110, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201003', 'FELDENE', 2000, 6);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201004', 'ADALATE', 130, 47);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201005', 'PROFENID', 140, 49);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201006', 'FELDENE', 155, 20);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201007', 'PROFENID', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201008', 'ADALATE', 200, 34);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201009', 'FELDENE', 123, 41);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201010', 'FELDENE', 144, 27);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201011', 'PROFENID', 56, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201012', 'ADALATE', 20001, 30);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201101', 'FELDENE', 152, 8);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201104', 'FELDENE', 774, 33);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201103', 'ASPEGIC', 132, 14);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201102', 'GLUCOPHAGE', 132, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201107', 'LOXEN', 114, 11);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201105', 'DOLIPRANE', 434, 117);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201106', 'GLUCOPHAGE', 321, 109);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201110', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201109', 'GLUCOPHAGE', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201108', 'AVLOCARDYL', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201111', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S2', '201112', 'DIAMICRON', 246, 13);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201001', 'ASPEGIC', 108, 25);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201002', 'ASPEGIC', 288, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201003', 'ADALATE', 238, 50);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201004', 'ASPEGIC', 163, 55);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201005', 'ASPEGIC', 200, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201006', 'ASPEGIC', 209, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201007', 'ADALATE', 111, 9);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201008', 'ASPEGIC', 112, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S3', '201009', 'ASPEGIC', 54, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'ASPEGIC', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'ASPEGIC', 292, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201003', 'ADALATE', 242, 53);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201004', 'ASPEGIC', 167, 58);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201005', 'ASPEGIC', 204, 61);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201006', 'ASPEGIC', 213, 15);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201007', 'ADALATE', 115, 12);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201008', 'ASPEGIC', 116, 48);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201009', 'FELDENE', 58, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201010', 'ASPEGIC', 47, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201011', 'GLUCOPHAGE', 10000, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201012', 'DIAMICRON', 846, 31);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201001', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201002', 'FELDENE', 112, 28);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S5', '201012', 'DIAMICRON', 2145, 26);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S7', '201110', 'GLUCOPHAGE', 4578, 45);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'DIAMICRON', 8461, 214);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'DIAMICRON', 1458, 124);

INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201102', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201110', 'ASPEGIC', 1245, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201112', 'FELDENE', 1457, 124);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201111', 'GLUCOPHAGE', 45789, 2457);
INSERT INTO D_VENTE_MEDICAMENTS
(SECTOR_ID, TIME_ID, ID_MEDICAMENT, CA, MARGE)
Values
('S4', '201101', 'ASPEGIC', 1456, 128);
COMMIT;
select * from D_VENTE_MEDICAMENTS where time_id=?20/10/2001?;







/********************************************/
/********************PARTIE 5****************/
/********************************************/

CREATE TABLE D_CLASSE_THERAPEUTIQUE
(
  ID_CLASSE_THERAPEUTIQUE  VARCHAR2(50)         NOT NULL,
  DESCRIPTION              VARCHAR2(50),
  TYPE_MEDICAMENT          VARCHAR2(50)
)
TABLESPACE USERS;



CREATE TABLE D_DIM_SECTOR
(
  SECTOR_ID               VARCHAR2(50)          NOT NULL,
  SITUATION_GEOGRAPHIQUE  VARCHAR2(50),
  LIB_SECT                VARCHAR2(50),
  PAYS                    VARCHAR2(50)
)
TABLESPACE USERS;


Insert into RNE.D_CLASSE_THERAPEUTIQUE
   (ID_CLASSE_THERAPEUTIQUE, DESCRIPTION, TYPE_MEDICAMENT)
 Values
   ('C1', 'ANTIDOULEUR (ASPIRINE)', 'ANTALGIQUES');
Insert into RNE.D_CLASSE_THERAPEUTIQUE
   (ID_CLASSE_THERAPEUTIQUE, DESCRIPTION, TYPE_MEDICAMENT)
 Values
   ('C2', 'ANTIBIOTIQUE', 'ANTIBIOTIQUE');
Insert into RNE.D_CLASSE_THERAPEUTIQUE
   (ID_CLASSE_THERAPEUTIQUE, DESCRIPTION, TYPE_MEDICAMENT)
 Values
   ('C3', 'TRAITEMENT POUR DIABETE', 'ANTIDIABETIQUES');
Insert into RNE.D_CLASSE_THERAPEUTIQUE
   (ID_CLASSE_THERAPEUTIQUE, DESCRIPTION, TYPE_MEDICAMENT)
 Values
   ('C4', 'TRAITEMENT DES HYPERTENDUS', 'ANTIHYPERTENSEURS');
Insert into RNE.D_CLASSE_THERAPEUTIQUE
   (ID_CLASSE_THERAPEUTIQUE, DESCRIPTION, TYPE_MEDICAMENT)
 Values
   ('C5', 'TRAITEMENT DES DOULEURS, FIEVRE', 'ANTIDOLEURS');
Insert into RNE.D_CLASSE_THERAPEUTIQUE
   (ID_CLASSE_THERAPEUTIQUE, DESCRIPTION, TYPE_MEDICAMENT)
 Values
   ('C6', 'OPHTALMOLOGIES', 'OPHTALMOLOGIES');
Insert into RNE.D_CLASSE_THERAPEUTIQUE
   (ID_CLASSE_THERAPEUTIQUE, DESCRIPTION, TYPE_MEDICAMENT)
 Values
   ('C7', 'RUMATHOLOGIE', 'RUMATHOLOGIE');
COMMIT;





 Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S5', 'NORD', 'NORD', 'ALLEMAGNE');
Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S6', 'OUEST', 'OUEST', 'ALLEMAGNE');
Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S7', 'EST', 'EST', 'ALLEMAGNE');
Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S8', 'SUD', 'SUD', 'ALLEMAGNE');
Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S1', 'NORD', 'NORD', 'FRANCE');
Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S2', 'OUEST', 'OUEST', 'FRANCE');
Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S3', 'EST', 'EST', 'FRANCE');
Insert into RNE.D_DIM_SECTOR
   (SECTOR_ID, SITUATION_GEOGRAPHIQUE, LIB_SECT, PAYS)
 Values
   ('S4', 'SUD', 'SUD', 'FRANCE');
COMMIT;




--a
select * from D_CLASSE_THERAPEUTIQUE order by ID_CLASSE_THERAPEUTIQUE;


--b
select sector_id, substr(time_id,1,4) as annee , sum(ca) as total_ca
from d_vente_medicaments group by sector_id, substr(time_id,1,4)
order by sector_id,substr(time_id,1,4);

--c
select A.pays,A.sector_id, A.SITUATION_GEOGRAPHIQUE, sum(B.ca) as total_ca
from D_DIM_SECTOR A ,  d_vente_medicaments B where A.sector_id = B.sector_id
group by A.pays,A.sector_id, A.SITUATION_GEOGRAPHIQUE;


--d
select A.id_classe_therapeutique from D_MEDICAMENTS A , d_vente_medicaments B
where A.id_medicament = B.id_medicament group by A.id_classe_therapeutique
order by A.id_classe_therapeutique;


--e
select * from (select sector_id , sum(ca) as total_ca from d_vente_medicaments
group by sector_id order by sector_id ) where total_ca > 8000  ;


--f
select B.sector_id, B.time_id,B.id_medicament, sum(B.ca) as ca, sum(B.marge) as marge
from D_DIM_SECTOR A ,  d_vente_medicaments B
where A.sector_id = B.sector_id and pays = 'FRANCE' and situation_geographique = 'SUD' and
(substr(time_id,5,6) = 10 or substr(time_id,5,6) =11 or  substr(time_id,5,6) = 12)
and substr(time_id,1,4) = 2011 group by B.sector_id, B.time_id,B.id_medicament
order by time_id ;


/********************************************/
/********************PARTIE 6****************/
/********************************************/


--1
select sector_id,substr(time_id,1,4), id_medicament,ca, rank() over (partition by substr(time_id,1,4),id_medicament order by ca asc) as ordre_ca_duminaumax from d_vente_medicaments where sector_id = 'S4' order by substr(time_id,1,4), id_medicament,ca;

--2
select sector_id, min(ca) as premier_ca ,max(ca) as dernier_ca from d_vente_medicaments group by sector_id ;

--3
select A.sector_id, A.id_medicament, A.sum_ca from
(select sector_id, id_medicament, sum(ca) as sum_ca from d_vente_medicaments group by sector_id, id_medicament order by sector_id asc, sum_ca desc) A
inner join
(select sector_id,max(sum_ca) as max_sum from (select sector_id, id_medicament, sum(ca) as sum_ca from d_vente_medicaments group by sector_id, id_medicament order by sector_id asc, sum_ca desc ) group by sector_id order by sector_id) B
on A.sum_ca = B.max_sum and A.sector_id = B.sector_id ;

--4
select B.sector_id, B.id_medicament ,A.ca, B.prem_val, B.dern_val
from d_vente_medicaments A ,
    (select sector_id, id_medicament , min(ca) as prem_val, max(ca) as dern_val
    from d_vente_medicaments group by sector_id ,id_medicament order by sector_id, id_medicament) B
where A.sector_id = B.sector_id  and B.id_medicament = B.id_medicament and (A.ca = B.prem_val or A.ca = B.dern_val)
order by B.sector_id , B.id_medicament, A.ca;

--5
select sector_id, id_medicament, ca, sum(ca) over ( order by sector_id , id_medicament ,ca) as ca_cumul from d_vente_medicaments order by sector_id, ca_cumul;
